### ISSUE TITLE
Problem getting google account info

### ISSUE THREAD

**Issue by aznutech-dev** [kishancool11/GoogleLoginMVC#1]
i tried the sample code when it return back from google then the following condition always  true

   var claimsPrincipal = HttpContext.User.Identity as ClaimsIdentity;

            var loginInfo = GoogleLoginViewModel.GetLoginInfo(claimsPrincipal);
            if (loginInfo == null)
            {
                return RedirectToAction("Index");
            }

**Comment by kishancool11** [comment]
Sorry for responding late. This code will return false in some only cases. Like when user denied the login permission or some error while grating the permission or claim is not sent by google. If everything works fine google will always give us claims and this code will returns true. 

Are you getting claims from google?

**Comment by aznutech-dev** [comment]
I started new project now it works. might be some configuration issue.
