### ISSUE TITLE
google Authentication don't appear !

### ISSUE THREAD

**Issue by SuperChuck83** [kishancool11/GoogleLoginMVC#4]
hello,
I follow step by steap your project but the google auth page never appear...

if i understand well it's the call of "SignIn" who redirect on google auth page isn't it ? 
just by doing it in :    **HttpContext.GetOwinContext().Authentication.Challenge(new AuthenticationProperties { RedirectUri = "Account/GoogleLoginCallback" }, "Google");**

Thank you

**Comment by kishancool11** [comment]
You need to configure Startup.cs page where in partial page detail configuration is there inside  ConfigureAuth Function.

 You need to configure Google account using method UseGoogleAuthentication which in Microsoft.Owin.Security.Google library. This library take care of calling correct google page.
